#!/bin/bash
#
# Create missing repository labels for Chained workflows
#
# This script creates the labels that are required by automated workflows
# but are currently missing from the repository, causing workflow failures.
#
# **@investigate-champion** identified these missing labels as the root cause
# of the workflow failures reported in the Workflow Health Alert.
#

set -e

REPO="enufacas/Chained"

echo "======================================================================="
echo "@investigate-champion: Creating Missing Repository Labels"
echo "======================================================================="
echo ""
echo "Repository: $REPO"
echo ""

# Check if GH_TOKEN or GITHUB_TOKEN is available
if [ -z "$GH_TOKEN" ] && [ -z "$GITHUB_TOKEN" ]; then
    echo "❌ Error: No GitHub token found"
    echo "   Please set GH_TOKEN or GITHUB_TOKEN environment variable"
    exit 1
fi

# Use GH_TOKEN if available, otherwise use GITHUB_TOKEN
export GH_TOKEN="${GH_TOKEN:-$GITHUB_TOKEN}"

echo "Creating labels..."
echo ""

# Label 1: chained-tv
# Used by: .github/workflows/chained_tv.yml (line 65)
echo "1. Creating 'chained-tv' label..."
gh label create "chained-tv" \
    --repo "$REPO" \
    --description "Automated Chained TV episode generation" \
    --color "7B68EE" \
    2>&1 | grep -v "already exists" || echo "   ✓ Label 'chained-tv' ready"

# Label 2: code-quality  
# Used by: .github/workflows/code-analyzer.yml (lines 158, 202)
echo "2. Creating 'code-quality' label..."
gh label create "code-quality" \
    --repo "$REPO" \
    --description "Code quality analysis and improvements" \
    --color "0E8A16" \
    2>&1 | grep -v "already exists" || echo "   ✓ Label 'code-quality' ready"

# Label 3: automated
# Used by: both workflows as a secondary label
echo "3. Creating 'automated' label..."
gh label create "automated" \
    --repo "$REPO" \
    --description "Automated workflow-generated content" \
    --color "FBCA04" \
    2>&1 | grep -v "already exists" || echo "   ✓ Label 'automated' ready"

# Label 4: ai-generated
# Used by: .github/workflows/code-analyzer.yml (line 202)
echo "4. Creating 'ai-generated' label..."
gh label create "ai-generated" \
    --repo "$REPO" \
    --description "Content generated by AI workflows" \
    --color "D4C5F9" \
    2>&1 | grep -v "already exists" || echo "   ✓ Label 'ai-generated' ready"

echo ""
echo "======================================================================="
echo "✅ Label Creation Complete"
echo "======================================================================="
echo ""
echo "@investigate-champion has successfully created all missing labels."
echo ""
echo "The following workflows should now run without label errors:"
echo "  • Chained TV Episode Generator (.github/workflows/chained_tv.yml)"
echo "  • Code Quality: Analyzer (.github/workflows/code-analyzer.yml)"
echo ""
echo "Failure rate should drop below 20% after these labels are in place."
echo ""
