#!/usr/bin/env python3
"""
Self-Documenting AI: Automatic Documentation from Discussions

This tool automatically generates documentation from GitHub issue discussions,
creating structured markdown files that capture insights, decisions, and patterns.

The system learns from issue discussions and creates:
1. Topic-based documentation files
2. Decision logs with rationale
3. Pattern catalogs
4. Best practices guides

Author: @create-botter (Nikola Tesla - Inventive and visionary)
Date: 2025-12-16
"""

import json
import os
import sys
import re
from pathlib import Path
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple
from collections import defaultdict, Counter
from dataclasses import dataclass, asdict

@dataclass
class DocumentationEntry:
    """Represents a self-documented insight from discussions"""
    id: str
    title: str
    category: str
    content: str
    source_issue: int
    source_discussion: str
    confidence: float
    tags: List[str]
    timestamp: str
    related_entries: List[str]
    
    def to_dict(self) -> Dict:
        return asdict(self)


class SelfDocumentingAI:
    """
    Automatically generates documentation from AI discussions.
    
    This system analyzes discussion insights and creates structured
    documentation that helps future AI agents learn from past conversations.
    """
    
    def __init__(
        self,
        discussions_dir: str = 'learnings/discussions',
        output_dir: str = 'docs/learnings'
    ):
        """
        Initialize the self-documenting AI system.
        
        Args:
            discussions_dir: Directory containing discussion JSON files
            output_dir: Directory to write generated documentation
        """
        self.discussions_dir = Path(discussions_dir)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        self.knowledge_graph_path = self.discussions_dir / 'knowledge_graph.json'
        self.knowledge_graph = self._load_knowledge_graph()
        
        # Documentation categories
        self.categories = {
            'agent_behavior': 'Agent System Behavior',
            'process': 'Development Processes',
            'technical_decision': 'Technical Decisions',
            'pattern': 'Code Patterns',
            'bug_fix': 'Bug Fixes and Solutions',
            'workflow': 'Workflow Patterns',
            'best_practice': 'Best Practices'
        }
        
    def _load_knowledge_graph(self) -> Dict:
        """Load the knowledge graph with insights"""
        if self.knowledge_graph_path.exists():
            with open(self.knowledge_graph_path, 'r') as f:
                return json.load(f)
        return {'insights': {}, 'connections': []}
    
    def extract_discussions(self) -> List[Dict]:
        """
        Extract all discussion files and their insights.
        
        Returns:
            List of discussion data dictionaries
        """
        discussions = []
        
        # Find all discussion JSON files
        for discussion_file in self.discussions_dir.glob('discussion_issue_*.json'):
            try:
                with open(discussion_file, 'r') as f:
                    discussion_data = json.load(f)
                    discussions.append(discussion_data)
            except Exception as e:
                print(f"⚠️ Error loading {discussion_file}: {e}")
                continue
        
        return discussions
    
    def categorize_insights(self, insights: List[Dict]) -> Dict[str, List[Dict]]:
        """
        Categorize insights by type for organized documentation.
        
        Args:
            insights: List of insight dictionaries
            
        Returns:
            Dictionary mapping categories to insights
        """
        categorized = defaultdict(list)
        
        for insight in insights:
            insight_type = insight.get('insight_type', 'general')
            categorized[insight_type].append(insight)
        
        return dict(categorized)
    
    def generate_topic_documentation(self, category: str, insights: List[Dict]) -> str:
        """
        Generate markdown documentation for a specific topic/category.
        
        Args:
            category: Category name
            insights: List of insights in this category
            
        Returns:
            Markdown formatted documentation
        """
        title = self.categories.get(category, category.replace('_', ' ').title())
        
        doc = f"# {title}\n\n"
        doc += f"> Auto-generated documentation from discussion insights  \n"
        doc += f"> Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')}  \n"
        doc += f"> Generated by: @create-botter (Self-Documenting AI)\n\n"
        
        doc += f"## Overview\n\n"
        doc += f"This document captures learnings and insights about **{title.lower()}** "
        doc += f"extracted from {len(insights)} issue discussions.\n\n"
        
        # Group insights by issue
        by_issue = defaultdict(list)
        for insight in insights:
            issue_num = insight.get('issue_number', 'unknown')
            by_issue[issue_num].append(insight)
        
        doc += f"## Insights by Discussion\n\n"
        doc += f"Total discussions: {len(by_issue)}\n\n"
        
        # Sort by issue number (newest first)
        sorted_issues = sorted(by_issue.keys(), reverse=True)
        
        for issue_num in sorted_issues[:20]:  # Limit to 20 most recent
            issue_insights = by_issue[issue_num]
            issue_title = issue_insights[0].get('issue_title', 'Unknown')
            
            doc += f"### Issue #{issue_num}: {issue_title}\n\n"
            
            for insight in issue_insights:
                content = insight.get('content', '').strip()
                if not content or len(content) < 10:
                    continue
                    
                confidence = insight.get('confidence', 0.5)
                tags = insight.get('tags', [])
                
                # Clean up content for display
                content = content.replace('\n', ' ')[:200]
                if len(content) >= 200:
                    content += '...'
                
                doc += f"- **{content}**\n"
                doc += f"  - *Confidence: {confidence:.0%}"
                if tags:
                    doc += f", Tags: {', '.join(tags)}"
                doc += "*\n\n"
        
        doc += f"## Key Patterns\n\n"
        
        # Extract common patterns from content
        all_content = ' '.join([i.get('content', '') for i in insights])
        words = re.findall(r'\b\w{4,}\b', all_content.lower())
        common_words = Counter(words).most_common(15)
        
        doc += f"Most frequent terms in this category:\n\n"
        for word, count in common_words:
            if word not in ['this', 'that', 'with', 'from', 'been', 'have', 'will']:
                doc += f"- **{word}** ({count} mentions)\n"
        
        doc += f"\n## Related Categories\n\n"
        doc += f"This topic may relate to:\n"
        for other_cat, other_title in self.categories.items():
            if other_cat != category:
                doc += f"- [{other_title}](./{other_cat}.md)\n"
        
        doc += f"\n---\n\n"
        doc += f"*Part of the Chained self-documenting AI system - Learning from every discussion* 🧠\n"
        
        return doc
    
    def generate_decision_log(self, insights: List[Dict]) -> str:
        """
        Generate a decision log from technical decision insights.
        
        Args:
            insights: List of technical decision insights
            
        Returns:
            Markdown formatted decision log
        """
        doc = "# Technical Decision Log\n\n"
        doc += f"> Auto-generated from discussion insights  \n"
        doc += f"> Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')}  \n\n"
        
        doc += "## Purpose\n\n"
        doc += "This log captures technical decisions made during development, "
        doc += "extracted from issue discussions and code reviews.\n\n"
        
        doc += "## Decisions\n\n"
        
        # Sort by confidence and timestamp
        sorted_insights = sorted(
            insights,
            key=lambda x: (x.get('confidence', 0), x.get('timestamp', '')),
            reverse=True
        )
        
        for idx, insight in enumerate(sorted_insights[:30], 1):
            content = insight.get('content', '').strip()
            if len(content) < 20:
                continue
            
            issue_num = insight.get('issue_number', 'N/A')
            timestamp = insight.get('timestamp', 'Unknown')
            confidence = insight.get('confidence', 0.5)
            
            doc += f"### Decision {idx}\n\n"
            doc += f"**Issue:** #{issue_num}  \n"
            doc += f"**Date:** {timestamp[:10] if timestamp else 'Unknown'}  \n"
            doc += f"**Confidence:** {confidence:.0%}  \n\n"
            doc += f"**Details:** {content}\n\n"
            doc += "---\n\n"
        
        return doc
    
    def generate_master_index(self, categories_generated: List[str]) -> str:
        """
        Generate a master index of all generated documentation.
        
        Args:
            categories_generated: List of category names that were documented
            
        Returns:
            Markdown formatted index
        """
        doc = "# Self-Documented AI Learnings Index\n\n"
        doc += f"> Auto-generated documentation from discussion insights  \n"
        doc += f"> Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')}  \n"
        doc += f"> Generated by: @create-botter\n\n"
        
        doc += "## 🎯 Purpose\n\n"
        doc += "This documentation is **automatically generated** from GitHub issue discussions. "
        doc += "The system extracts insights, patterns, and decisions from real conversations "
        doc += "and creates structured knowledge for future reference.\n\n"
        
        doc += "## 📚 Available Documentation\n\n"
        
        for category in categories_generated:
            title = self.categories.get(category, category.replace('_', ' ').title())
            doc += f"- **[{title}](./{category}.md)** - Insights about {title.lower()}\n"
        
        doc += "\n## 🔍 How This Works\n\n"
        doc += "1. **Discussion Analysis** - AI agents discuss issues and PRs\n"
        doc += "2. **Insight Extraction** - Key learnings are identified automatically\n"
        doc += "3. **Documentation Generation** - This tool creates structured docs\n"
        doc += "4. **Continuous Updates** - Docs refresh as new discussions occur\n\n"
        
        doc += "## 📊 Statistics\n\n"
        doc += f"- **Categories documented:** {len(categories_generated)}\n"
        doc += f"- **Last generation:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
        doc += f"- **Source:** learnings/discussions/knowledge_graph.json\n\n"
        
        doc += "---\n\n"
        doc += "*Self-documenting AI in action - Learning never stops* 🚀\n"
        
        return doc
    
    def generate_all_documentation(self) -> Dict[str, str]:
        """
        Generate all documentation files from discussions.
        
        Returns:
            Dictionary mapping filenames to content
        """
        print("📚 Starting documentation generation...")
        
        # Extract insights from knowledge graph
        insights = self.knowledge_graph.get('insights', {})
        print(f"Found {len(insights)} insights in knowledge graph")
        
        if not insights:
            print("⚠️ No insights found. Loading from discussion files...")
            discussions = self.extract_discussions()
            print(f"Found {len(discussions)} discussion files")
            
            # Extract insights from discussions
            all_insights = []
            for disc in discussions:
                disc_insights = disc.get('insights', [])
                all_insights.extend(disc_insights)
            
            # Convert to dict format
            insights = {f"insight_{i}": ins for i, ins in enumerate(all_insights)}
            print(f"Extracted {len(insights)} insights from discussions")
        
        # Categorize insights
        categorized = defaultdict(list)
        for insight_id, insight in insights.items():
            insight_type = insight.get('insight_type', 'general')
            categorized[insight_type].append(insight)
        
        print(f"Categorized into {len(categorized)} categories")
        
        # Generate documentation for each category
        generated_docs = {}
        categories_with_docs = []
        
        for category, category_insights in categorized.items():
            if len(category_insights) < 3:
                print(f"⏭️  Skipping {category} (only {len(category_insights)} insights)")
                continue
            
            print(f"📝 Generating documentation for: {category} ({len(category_insights)} insights)")
            
            doc_content = self.generate_topic_documentation(category, category_insights)
            filename = f"{category}.md"
            generated_docs[filename] = doc_content
            categories_with_docs.append(category)
        
        # Generate decision log if we have technical decisions
        tech_decisions = categorized.get('technical_decision', [])
        if len(tech_decisions) >= 3:
            print(f"📋 Generating decision log ({len(tech_decisions)} decisions)")
            decision_log = self.generate_decision_log(tech_decisions)
            generated_docs['decision_log.md'] = decision_log
        
        # Generate master index
        print("📑 Generating master index")
        index_content = self.generate_master_index(categories_with_docs)
        generated_docs['README.md'] = index_content
        
        return generated_docs
    
    def write_documentation(self, docs: Dict[str, str]) -> int:
        """
        Write generated documentation to files.
        
        Args:
            docs: Dictionary mapping filenames to content
            
        Returns:
            Number of files written
        """
        files_written = 0
        
        for filename, content in docs.items():
            filepath = self.output_dir / filename
            
            try:
                with open(filepath, 'w') as f:
                    f.write(content)
                print(f"✅ Wrote: {filepath}")
                files_written += 1
            except Exception as e:
                print(f"❌ Error writing {filepath}: {e}")
        
        return files_written
    
    def run(self) -> int:
        """
        Run the complete documentation generation process.
        
        Returns:
            Number of documentation files generated
        """
        print("\n🚀 Self-Documenting AI - Starting...")
        print(f"📂 Discussions: {self.discussions_dir}")
        print(f"📁 Output: {self.output_dir}\n")
        
        # Generate all documentation
        docs = self.generate_all_documentation()
        
        # Write to files
        files_written = self.write_documentation(docs)
        
        print(f"\n✨ Complete! Generated {files_written} documentation files")
        print(f"📍 Documentation available at: {self.output_dir}\n")
        
        return files_written


def main():
    """Main entry point"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Generate documentation automatically from AI discussions'
    )
    parser.add_argument(
        '--discussions-dir',
        default='learnings/discussions',
        help='Directory containing discussion JSON files'
    )
    parser.add_argument(
        '--output-dir',
        default='docs/learnings',
        help='Directory to write generated documentation'
    )
    
    args = parser.parse_args()
    
    # Create and run the self-documenting AI
    doc_generator = SelfDocumentingAI(
        discussions_dir=args.discussions_dir,
        output_dir=args.output_dir
    )
    
    files_generated = doc_generator.run()
    
    # Exit with success if files were generated
    return 0 if files_generated > 0 else 1


if __name__ == '__main__':
    sys.exit(main())
